#version: '3'
#services:
#  mysql:
#    image: mysql
#    container_name: mysql-container
#    restart: always
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=test
#      - MYSQL_DATABASE=test
#      - MYSQL_CHARSET=utf8mb4
#      - MYSQL_COLLATION=utf8mb4_unicode_ci
#    command:
#      - "mysqld"
#      - "--character-set-server=utf8mb4"
#      - "--collation-server=utf8mb4_unicode_ci"
#
#  springboot:
#    build: .
#    container_name: my-api-container
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#    restart:
#      always
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
#      - SPRING_DATASOURCE_USERNAME=test
#      - SPRING_DATASOURCE_PASSWORD=test