spring:
  config:
    activate:
      on-profile: local

  r2dbc:
    url: jdbc:postgresql://localhost:5432/test_db
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
    database-platform: postgresql