spring:
  config:
    activate:
      on-profile: local

  data:
    r2dbc:
      repositories:
        enabled: true

  r2dbc:
    url: r2dbc:mysql://localhost:3306/test_db?useUnicode=true&serverTimezone=UTC
    username: test
    password: test

logging:
  level:

    org.springframework.r2dbc.core: debug